[32m2023-06-02 14:00:10 -0400[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 27f4ea64-d61f-4672-a5a9-ff742fd12738 - 65254 - LOGS_CAPTURED - Started capturing logs in process (pid: 65254).
[32m2023-06-02 14:00:10 -0400[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 27f4ea64-d61f-4672-a5a9-ff742fd12738 - 65254 - acsVars - STEP_START - Started execution of step "acsVars".
[32m2023-06-02 14:00:10 -0400[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 27f4ea64-d61f-4672-a5a9-ff742fd12738 - acsVars - Loading file from: /Users/blakevanfleteren/Programs/GitHub/vaccine_data/vaccines/tmpbd1xor13/storage/years
[32m2023-06-02 14:00:10 -0400[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 27f4ea64-d61f-4672-a5a9-ff742fd12738 - 65254 - acsVars - ASSET_OBSERVATION - ASSET_OBSERVATION for step acsVars
[32m2023-06-02 14:00:10 -0400[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 27f4ea64-d61f-4672-a5a9-ff742fd12738 - 65254 - acsVars - LOADED_INPUT - Loaded input "years" using input manager "io_manager"
[32m2023-06-02 14:00:10 -0400[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 27f4ea64-d61f-4672-a5a9-ff742fd12738 - 65254 - acsVars - STEP_INPUT - Got input "years" of type "[Any]". (Type check passed).
[32m2023-06-02 14:00:12 -0400[0m - dagster - [34mERROR[0m - [31m__ASSET_JOB - 27f4ea64-d61f-4672-a5a9-ff742fd12738 - 65254 - acsVars - STEP_FAILURE - Execution of step "acsVars" failed.

dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "acsVars"::

requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Stack Trace:
  File "/Users/blakevanfleteren/Programs/GitHub/vaccine_data/.venv/lib/python3.9/site-packages/dagster/_core/execution/plan/utils.py", line 54, in op_execution_error_boundary
    yield
  File "/Users/blakevanfleteren/Programs/GitHub/vaccine_data/.venv/lib/python3.9/site-packages/dagster/_utils/__init__.py", line 445, in iterate_with_context
    next_output = next(iterator)
  File "/Users/blakevanfleteren/Programs/GitHub/vaccine_data/.venv/lib/python3.9/site-packages/dagster/_core/execution/plan/compute_generator.py", line 124, in _coerce_op_compute_fn_to_iterator
    result = invoke_compute_fn(
  File "/Users/blakevanfleteren/Programs/GitHub/vaccine_data/.venv/lib/python3.9/site-packages/dagster/_core/execution/plan/compute_generator.py", line 118, in invoke_compute_fn
    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)
  File "/Users/blakevanfleteren/Programs/GitHub/vaccine_data/vaccines/vaccines/assets.py", line 102, in acsVars
    variables[year] = response.json()['variables']
  File "/Users/blakevanfleteren/Programs/GitHub/vaccine_data/.venv/lib/python3.9/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)

The above exception occurred during handling of the following exception:
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Stack Trace:
  File "/Users/blakevanfleteren/Programs/GitHub/vaccine_data/.venv/lib/python3.9/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Users/blakevanfleteren/.pyenv/versions/3.9.7/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/Users/blakevanfleteren/.pyenv/versions/3.9.7/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/blakevanfleteren/.pyenv/versions/3.9.7/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None

The above exception occurred during handling of the following exception:
StopIteration: 0

Stack Trace:
  File "/Users/blakevanfleteren/.pyenv/versions/3.9.7/lib/python3.9/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
[0m
